import type { Student, Strategy, Tweaks } from '@/types';

export const DATA_VERSION = '2';

export const ACCENT_PALETTES: Record<string, Record<string, string>> = {
  blue:    { accent: '#0570de', 'accent-600': '#0050b8', 'accent-50': '#eff6ff', 'accent-100': '#dbeafe' },
  indigo:  { accent: '#635bff', 'accent-600': '#5851e6', 'accent-50': '#f3f2ff', 'accent-100': '#e7e5ff' },
  slate:   { accent: '#334155', 'accent-600': '#1e293b', 'accent-50': '#f1f5f9', 'accent-100': '#e2e8f0' },
  emerald: { accent: '#059669', 'accent-600': '#047857', 'accent-50': '#ecfdf5', 'accent-100': '#d1fae5' },
};

export const TWEAK_DEFAULTS: Tweaks = {
  nav: 'top',
  density: 'comfortable',
  cardStyle: 'bordered',
  accent: 'indigo',
};

export const COMMON_APP_CATEGORIES = [
  'Academic', 'Art', 'Athletics: Club', 'Athletics: JV/Varsity', 'Career Oriented',
  'Community Service (Volunteer)', 'Cultural', 'Computer/Technology', 'Dance', 'Debate/Speech',
  'Environmental', 'Family Responsibilities', 'Foreign Exchange', 'Foreign Language', 'Internship',
  'Journalism/Publication', 'Junior R.O.T.C.', 'LGBT', 'Music: Instrumental', 'Music: Vocal',
  'Religious', 'Research', 'Robotics', 'School Spirit', 'Science/Math', 'Social Justice',
  'Student Govt./Politics', 'Theater/Drama', 'Work (Paid)', 'Other Club/Activity',
];

export const LOADING_STEPS = [
  'Parsing applicant profile',
  'Cross-referencing peer admit cohorts',
  'Modeling Reach / Match / Safety probabilities',
  'Drafting positioning narrative',
  'Building month-by-month execution plan',
];

export const SAMPLE_STUDENTS: Student[] = [
  {
    id: 's7',
    name: 'Ethan Li',
    grade: 11,
    school: 'Highland Park High School',
    city: 'Dallas, TX',
    major: 'Computer Science / AI Systems',
    secondary: 'Mathematics',
    gpa: '4.505',
    gpaType: 'Weighted',
    sat: '1540',
    act: '',
    apCount: 13,
    classRank: 'DNR',
    graduationProgram: 'Foundation High School Program',
    endorsements: [
      'Multidisciplinary Studies (Pursued)',
      'Distinguished Level of Achievement (Pursued)',
    ],
    stateAssessments: [
      'English I EOC — Masters (Spring 2024)',
      'English II EOC — Masters (Spring 2025)',
      'Biology EOC — Masters (Spring 2024)',
      'Algebra I EOC — Masters (Spring 2022)',
    ],
    performanceAcknowledgements: [
      'Information Technology Specialist — Python',
      'AP Biology acknowledgement',
      'AP Chemistry acknowledgement',
      'AP Computer Science Principles acknowledgement',
      'AP Calculus AB acknowledgement',
      'AP World History acknowledgement',
      'PSAT/NMSQT Commended Scholar or National Recognition Program acknowledgement',
      'SAT total score of at least 1350 acknowledgement',
      'Information Technology Specialist — Java',
    ],
    strengths: ['AI/ML Systems', 'Competitive Programming', 'Full-Stack Engineering', 'Research & Innovation'],
    weak: ['SAT below top-10 median', 'Limited humanities depth', 'No published research paper'],
    citizenship: 'U.S. Citizen',
    schoolType: 'Public',
    competitiveness: 'Very Competitive',
    firstGen: 'No',
    targetRange: 'Top 10',
    risk: 'Balanced',
    preferred: 'MIT, Stanford, CMU, Caltech',
    traits: 'AI Systems Builder with production-scale deployments across speech processing, financial reasoning, and human-AI interaction. Built Whisper→LLM→XTTS speech therapy pipeline achieving 46% fluency improvement. USACO Gold Division. 100+ volunteer service hours.',
    angles: 'Three deployed AI systems targeting real-world problems; USACO Gold via perfect-score promotion; science fair winner with societal impact framing (pediatric speech therapy accessibility)',
    color: '#0ea5e9',
    status: 'Draft',
    updated: 'Jul 2026',
    activities: [
      {
        id: 'a1',
        category: 'Research',
        position: 'Founder & Lead Developer',
        org: 'SpeakWise',
        desc: 'Built multi-stage neural speech repair system (Whisper→LLM→XTTS); 46% fluency improvement, 95%+ stutter reduction targeting pediatric accessibility',
        grades: [11, 12],
        timing: 'School Year, Summer',
        hours: 15,
        weeks: 40,
      },
      {
        id: 'a2',
        category: 'Internship',
        position: 'Software Engineer Intern',
        org: 'Eelocutionist',
        desc: 'Built production AI interview coaching platform with Express.js + LLM evaluation, speech APIs, and multi-format interview engine deployed to live users',
        grades: [11, 12],
        timing: 'School Year, Summer',
        hours: 10,
        weeks: 36,
      },
      {
        id: 'a3',
        category: 'Research',
        position: 'Independent Developer',
        org: 'Zeitgeist (Independent Project)',
        desc: 'Built real-time AI system for financial reasoning under uncertainty; integrated Polygon.io options data with LLM interpretation via FastAPI + Docker',
        grades: [11, 12],
        timing: 'School Year, Summer',
        hours: 8,
        weeks: 30,
      },
      {
        id: 'a4',
        category: 'Science/Math',
        position: 'Gold Division Competitor',
        org: 'USA Computing Olympiad (USACO)',
        desc: 'Achieved Gold Division via perfect-score promotion from Silver; competitive programming in C++ and Python through LeetCode and Codeforces',
        grades: [10, 11, 12],
        timing: 'School Year',
        hours: 5,
        weeks: 36,
      },
      {
        id: 'a5',
        category: 'Community Service (Volunteer)',
        position: 'Volunteer',
        org: 'Multiple Community Organizations',
        desc: 'Completed 100+ hours of community service earning Gold President\'s Volunteer Service Award and International Service Honor Recognition (Gold)',
        grades: [10, 11, 12],
        timing: 'School Year, Summer',
        hours: 4,
        weeks: 30,
      },
      {
        id: 'a6',
        category: 'Cultural',
        position: 'Member, CS Chapter',
        org: 'Asian Culture and Education Society USA',
        desc: 'Youth Board of Governors, Computer Science Chapter; leadership in student technical and cultural organizations',
        grades: [11, 12],
        timing: 'School Year',
        hours: 3,
        weeks: 36,
      },
    ],
    awards: [
      {
        id: 'w1',
        title: 'USACO Gold Division',
        grade: 11,
        level: 'National',
      },
      {
        id: 'w2',
        title: 'HPHS SciTech Fair — 1st Place & Jay Ingram Award (SpeakWise)',
        grade: 11,
        level: 'School',
      },
      {
        id: 'w3',
        title: 'Dallas Regional Science & Engineering Fair (DRSEF) — Honorable Mention, Top 4',
        grade: 11,
        level: 'Regional',
      },
      {
        id: 'w4',
        title: 'President\'s Volunteer Service Award — Gold (100+ hrs)',
        grade: 11,
        level: 'National',
      },
      {
        id: 'w5',
        title: 'International Service Honor Recognition — Gold Award',
        grade: 11,
        level: 'National',
      },
      {
        id: 'w6',
        title: 'Scholastic Writing Awards — Regional Silver Key',
        grade: 11,
        level: 'Regional',
      },
      {
        id: 'w7',
        title: 'CTY Johns Hopkins Talent Search — Advanced Level Qualification',
        grade: 10,
        level: 'National',
      },
      {
        id: 'w8',
        title: 'PSAT/NMSQT Commended Scholar or National Recognition Program acknowledgement',
        grade: 11,
        level: 'National',
      },
      {
        id: 'w9',
        title: 'Information Technology Specialist Certifications - Python and Java',
        grade: 11,
        level: 'Regional',
      },
    ],
    courses: [
      // Grades transcribed from the official final Grade-11 record (State of Texas AAR, printed 06/11/2026).
      { id: 'c1', name: 'English I', level: 'Honors', gradeSem1: '95', gradeSem2: '88', year: 9 },
      { id: 'c2', name: 'English II', level: 'Honors', gradeSem1: '96', gradeSem2: '96', year: 10 },
      { id: 'c3', name: 'AP English Language', level: 'AP', gradeSem1: '94', gradeSem2: '91', year: 11 },
      { id: 'c4', name: 'Chinese I', level: 'Regular', gradeSem1: '92', gradeSem2: '92', year: 9 },
      { id: 'c5', name: 'Latin I', level: 'Honors', gradeSem1: '95', gradeSem2: '93', year: 9 },
      { id: 'c6', name: 'Latin II', level: 'Honors', gradeSem1: '93', gradeSem2: '93', year: 10 },
      { id: 'c7', name: 'Latin III', level: 'Honors', gradeSem1: '96', gradeSem2: '96', year: 10 },
      { id: 'c8', name: 'Latin IV', level: 'AP', gradeSem1: '96', gradeSem2: '99', year: 11 },
      { id: 'c9', name: 'Algebra I', level: 'Regular', gradeSem1: '77', gradeSem2: '82', year: 9 },
      { id: 'c10', name: 'Geometry', level: 'Regular', gradeSem1: '80', gradeSem2: '79', year: 9 },
      { id: 'c11', name: 'Algebra II', level: 'Honors', gradeSem1: '88', gradeSem2: '91', year: 9 },
      { id: 'c12', name: 'AP Calculus AB', level: 'AP', gradeSem1: '87', gradeSem2: '88', year: 10 },
      { id: 'c13', name: 'Precalculus', level: 'Regular', gradeSem1: '91', gradeSem2: '92', year: 10 },
      { id: 'c14', name: 'AP Calculus BC', level: 'AP', gradeSem1: '93', gradeSem2: '91', year: 11 },
      { id: 'c15', name: 'AP Statistics', level: 'AP', gradeSem1: '97', gradeSem2: '92', year: 11 },
      { id: 'c16', name: 'Biology', level: 'Honors', gradeSem1: '92', gradeSem2: '93', year: 9 },
      { id: 'c17', name: 'Chemistry', level: 'Honors', gradeSem1: '90', gradeSem2: '91', year: 9 },
      { id: 'c18', name: 'AP Biology', level: 'AP', gradeSem1: '92', gradeSem2: '93', year: 10 },
      { id: 'c19', name: 'AP Chemistry', level: 'AP', gradeSem1: '93', gradeSem2: '96', year: 10 },
      { id: 'c20', name: 'AP Physics C: Electricity and Magnetism', level: 'AP', gradeSem1: '95', gradeSem2: '94', year: 11 },
      { id: 'c21', name: 'AP Physics C: Mechanics', level: 'AP', gradeSem1: '95', gradeSem2: '94', year: 11 },
      { id: 'c22', name: 'World Geography', level: 'Honors', gradeSem1: '96', gradeSem2: '93', year: 9 },
      { id: 'c23', name: 'AP World History', level: 'AP', gradeSem1: '91', gradeSem2: '90', year: 10 },
      { id: 'c24', name: 'AP US History', level: 'AP', gradeSem1: '94', gradeSem2: '96', year: 11 },
      { id: 'c25', name: 'AP Computer Science Principles', level: 'AP', gradeSem1: '98', gradeSem2: '98', year: 10 },
      { id: 'c26', name: 'AP Computer Science A', level: 'AP', gradeSem1: '93', gradeSem2: '93', year: 11 },
      { id: 'c27', name: 'Professional Communications', level: 'Regular', gradeSem1: '87', gradeSem2: '', year: 9 },
      { id: 'c28', name: 'Health Education', level: 'Regular', gradeSem1: '92', gradeSem2: '', year: 9 },
      { id: 'c29', name: 'Lifetime Fitness', level: 'Regular', gradeSem1: '90', gradeSem2: '96', year: 9 },
      { id: 'c30', name: 'Art I', level: 'Regular', gradeSem1: '96', gradeSem2: '91', year: 9 },
    ],
  },
  {
    id: 's1',
    name: 'Aarav Patel',
    grade: 11,
    school: 'Mission San Jose High School',
    city: 'Fremont, CA',
    major: 'Computer Science',
    secondary: 'Mathematics',
    gpa: '4.62',
    gpaType: 'Weighted',
    sat: '1560',
    act: '',
    apCount: 11,
    strengths: ['Mathematics', 'Computer Science', 'Physics'],
    weak: [],
    citizenship: 'U.S. Citizen',
    schoolType: 'Public',
    competitiveness: 'Top',
    firstGen: 'No',
    targetRange: 'Top 10',
    risk: 'Aggressive',
    preferred: 'MIT, Stanford, CMU, UC Berkeley',
    traits: 'Independent researcher, deeply curious, builds end-to-end systems. Prefers depth over breadth.',
    angles: 'Self-taught ML researcher who shipped a published arXiv preprint in 11th grade. Built a tutoring nonprofit reaching 400+ students in underserved Bay Area districts.',
    color: '#6366f1',
    status: 'Strategy Generated',
    updated: '2 hours ago',
    activities: [
      { id: 'a1', category: 'Academic', position: 'Founder & Lead Researcher', org: 'Riemann ML Lab (independent)', desc: 'Published arXiv preprint on transformer interpretability; cited 12x. Mentored 6 peers in research methodology.', grades: [10, 11], timing: 'All Year', hours: 15, weeks: 40 },
      { id: 'a2', category: 'Computer/Technology', position: 'Founder, Executive Director', org: 'CodeForward Tutoring', desc: 'Built 501(c)(3) serving 400+ students across 8 Title I schools. Raised $32K in grants; led team of 24 tutors.', grades: [10, 11], timing: 'All Year', hours: 8, weeks: 38 },
      { id: 'a3', category: 'Science/Math', position: 'USAMO Qualifier', org: 'Mathematical Association of America', desc: 'Top 250 nationally on AIME (score: 12). USAMO qualifier 2025. Member of school\'s #1-ranked AMC team.', grades: [10, 11], timing: 'All Year', hours: 6, weeks: 30 },
    ],
    awards: [
      { id: 'w1', title: 'USAMO Qualifier (Top 250 nationally)', grade: 11, level: 'National' },
      { id: 'w2', title: 'Regeneron STS Semifinalist', grade: 11, level: 'National' },
      { id: 'w3', title: 'Coca-Cola Scholar Semifinalist', grade: 11, level: 'National' },
    ],
  },
  {
    id: 's2',
    name: 'Sofia Reyes',
    grade: 12,
    school: 'Stuyvesant High School',
    city: 'New York, NY',
    major: 'Bioengineering',
    secondary: 'Public Health',
    gpa: '3.97',
    gpaType: 'Unweighted',
    sat: '1540',
    act: '',
    apCount: 9,
    strengths: ['Biology', 'Chemistry', 'Spanish'],
    weak: ['Physics'],
    citizenship: 'U.S. Citizen',
    schoolType: 'Public',
    competitiveness: 'Top',
    firstGen: 'Yes',
    targetRange: 'Top 20',
    risk: 'Balanced',
    preferred: 'Johns Hopkins, Duke, Rice, UT Austin',
    traits: '',
    angles: '',
    color: '#ec4899',
    status: 'Document Ready',
    updated: 'Yesterday',
    activities: [],
    awards: [],
  },
  {
    id: 's3',
    name: 'Marcus Chen',
    grade: 11,
    school: 'Thomas Jefferson HSST',
    city: 'Alexandria, VA',
    major: 'Electrical Engineering',
    secondary: 'Robotics',
    gpa: '4.48',
    gpaType: 'Weighted',
    sat: '1520',
    act: '34',
    apCount: 8,
    strengths: ['Physics', 'Mathematics'],
    weak: [],
    citizenship: 'U.S. Citizen',
    schoolType: 'Public',
    competitiveness: 'Top',
    firstGen: 'No',
    targetRange: 'Top 10',
    risk: 'Balanced',
    preferred: 'MIT, Caltech, Georgia Tech',
    traits: '',
    angles: '',
    color: '#0891b2',
    status: 'Draft',
    updated: '3 days ago',
    activities: [],
    awards: [],
  },
  {
    id: 's4',
    name: 'Priya Krishnan',
    grade: 11,
    school: 'Phillips Exeter Academy',
    city: 'Exeter, NH',
    major: 'Economics',
    secondary: 'Statistics',
    gpa: '3.92',
    gpaType: 'Unweighted',
    sat: '1570',
    act: '',
    apCount: 0,
    strengths: ['Economics', 'Statistics', 'Writing'],
    weak: [],
    citizenship: 'U.S. Citizen',
    schoolType: 'Private',
    competitiveness: 'Top',
    firstGen: 'No',
    targetRange: 'Top 10',
    risk: 'Aggressive',
    preferred: 'Harvard, Stanford, Princeton, Yale',
    traits: '',
    angles: '',
    color: '#7c3aed',
    status: 'Strategy Generated',
    updated: '5 days ago',
    activities: [],
    awards: [],
  },
  {
    id: 's5',
    name: 'Daniel Okafor',
    grade: 12,
    school: 'Lincoln Park High School',
    city: 'Chicago, IL',
    major: 'Mechanical Engineering',
    secondary: '',
    gpa: '4.31',
    gpaType: 'Weighted',
    sat: '1490',
    act: '',
    apCount: 7,
    strengths: ['Engineering', 'Physics'],
    weak: [],
    citizenship: 'U.S. Citizen',
    schoolType: 'Public',
    competitiveness: 'Average',
    firstGen: 'Yes',
    targetRange: 'Top 20',
    risk: 'Conservative',
    preferred: 'Georgia Tech, UIUC, Purdue',
    traits: '',
    angles: '',
    color: '#059669',
    status: 'Document Ready',
    updated: '1 week ago',
    activities: [],
    awards: [],
  },
];

export const INITIAL_STRATEGIES: Record<string, Strategy> = {
  s1: {
    positioning: {
      type: 'Specialist Researcher — STEM Builder',
      identity: 'Self-directed ML researcher with a published preprint and a measurable impact narrative through a 400-student tutoring nonprofit. Profile reads as "graduate-bound undergraduate" rather than typical applicant.',
      strengths: [
        'Published research output (arXiv preprint, 12 citations) — extraordinarily rare at HS level',
        'Tier-1 industry experience (Anthropic) with shipped, merged code',
        'USAMO qualification + Regeneron STS semifinalist — two independent national signals',
        'Demonstrated leadership via 501(c)(3) with $32K raised and 24-tutor team',
      ],
      weaknesses: [
        'No humanities/writing signal — risk of "STEM-only" read at holistic schools (Harvard, Yale)',
        'Activities list reads research-heavy; Common App reviewers may want one personal-passion item',
        'Recommender variety unconfirmed — needs at least one non-STEM teacher rec',
      ],
    },
    competitiveness: {
      top10: { level: 'Medium-High', note: 'Strong at MIT/CMU/Caltech; softer at HYP without humanities counterweight' },
      top20: { level: 'High', note: 'Cornell, Duke, Hopkins, Rice all align with research narrative' },
      top50: { level: 'Very High', note: 'Effectively a near-lock at any flagship state school for CS' },
      bullets: [
        'Research + industry + nonprofit triad is the single strongest known proxy for top-10 CS admissions; only 4–6% of admitted CS applicants present all three.',
        '1560 SAT and 4.62W GPA are above the 75th percentile for every target school except Stanford SCEA pool.',
        'First-choice schools should be ones that explicitly value research depth: MIT, CMU SCS, Stanford CS, Berkeley EECS.',
      ],
    },
    schools: {
      reach: [
        { name: 'MIT', chance: '22%', note: 'Best-fit reach; research narrative aligns with EECS culture' },
        { name: 'Stanford', chance: '9%', note: 'REA recommended; hardest yield without humanities anchor' },
        { name: 'Carnegie Mellon SCS', chance: '14%', note: 'ED would lift to ~28%' },
        { name: 'Caltech', chance: '11%', note: 'USAMO + STS is exact archetype Caltech selects for' },
      ],
      match: [
        { name: 'UC Berkeley EECS', chance: '32%', note: 'In-state CA; uncapped applicant; strong fit' },
        { name: 'Cornell CoE', chance: '38%', note: 'ED would lift to ~55%' },
        { name: 'Georgia Tech CS', chance: '55%', note: 'OOS but research alignment is strong' },
      ],
      safety: [
        { name: 'UT Austin Turing', chance: '—', note: 'Apply to Turing Scholars; main CS as backup' },
        { name: 'Rice CS', chance: '62%', note: 'Smaller pool, research-friendly faculty' },
        { name: 'UC San Diego CS', chance: '75%', note: 'True academic safety with research opps' },
      ],
    },
    strategy: {
      ed_ea: 'REA Stanford OR ED CMU SCS — pick one. Recommendation: ED Carnegie Mellon SCS. CMU\'s research culture is the cleanest narrative fit, ED yield rate is materially higher than RD, and Stanford REA realistically gives a 1.4x bump vs CMU ED\'s 2x bump. EA: MIT, Caltech, Georgia Tech, UMich, UT Austin (all non-restrictive).',
      narrative: 'Position as "researcher who builds infrastructure for others to learn." Tutoring nonprofit + open-source curriculum + arXiv preprint together tell one story: democratizing access to ML research. Personal essay should center the moment Aarav realized publishing didn\'t matter without distribution — leading to the curriculum project. Avoid "I love coding since age 7" framing.',
    },
    plan: [
      { month: 'May 2026', tasks: 'Finalize Common App Personal Statement draft 1. Lock teacher recommenders (1 STEM, 1 non-STEM). Complete Anthropic write-up for activities list.' },
      { month: 'Jun 2026', tasks: 'Submit Regeneron STS continuation. Begin CMU SCS supplemental drafts. Draft "Why CMU" and "maker" essays.' },
      { month: 'Jul 2026', tasks: 'Visit MIT, CMU, Cornell campuses. Schedule alumni interviews where available. Begin MIT supplements.' },
      { month: 'Aug 2026', tasks: 'Submit ED Carnegie Mellon SCS by 11/1. Polish Personal Statement final. Lock all rec letters.' },
      { month: 'Sep 2026', tasks: 'Submit EA applications: MIT, Caltech, Georgia Tech, UMich, UT Austin Turing.' },
      { month: 'Oct 2026', tasks: 'Push hardest on Stanford REA decision (deadline 11/1). Mid-month: confirm all rec letters submitted.' },
      { month: 'Nov 2026', tasks: 'ED CMU decision arrives mid-Dec. If admitted: withdraw all other apps. If deferred/denied: complete remaining RD apps.' },
      { month: 'Dec 2026 – Jan 2027', tasks: 'Final RD push. Submit FAFSA + CSS Profile. Continue research output.' },
    ],
  },
};
